apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::997312036829:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1BJJDRIORNP1F
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::997312036829:role/UdacityFlaskDeployCBKubectlRole
      username: build_role_arn  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-31T19:06:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1581"
  uid: da0204fe-aa57-4aef-9e0a-806ff2d72f55